name: fin_econ_2025

dependencies:
  - notebook
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - numba
  - pandas-datareader
  - scipy
  - statsmodels
  - seaborn
  - pip
  - pip:
      - yfinance
      - fredapi
      - wrds
      - matplotlib
      - sympy
      - cvxopt
      - cvxpy
      - arch
      - scikit-learn
      - ipympl
      - tidyfinance